app:
  encoding: @project.build.sourceEncoding@
  java:
    version: @java.version@
spring:
  application:
    name: filesystem
  jackson:
    deserialization:
      use_java_array_for_json_array: true
  resources:
    cache-period: 0
server:
    port: 8080
